TOPDIR				=	..
include					$(TOPDIR)/mk/color.mk	# must include, or no color

TARGET_EXE			= 		Hello
# ------------------------------------------------------------------
# ◆ファイル
# ------------------------------------------------------------------
OBJS				=	main.cpp

.PHONY:			Hello

all:					$(TARGET_EXE)
include					$(TOPDIR)/mk/target.mk
